/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 main.gltf -k 
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/main.gltf')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera name="Camera" makeDefault={false} far={100} near={0.1} fov={22.895} position={[7.863, 0.921, -0.104]} rotation={[-1.72, 1.443, 1.721]} />
      <mesh name="text_sake" geometry={nodes.text_sake.geometry} material={sixth_texture_atlas_material} position={[5.386, 1.036, 0.745]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="text_creative_developer" geometry={nodes.text_creative_developer.geometry} material={sixth_texture_atlas_material} position={[5.343, 1.022, -0.831]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="text_summit" geometry={nodes.text_summit.geometry} material={sixth_texture_atlas_material} position={[5.361, 0.146, -0.039]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="text_x" geometry={nodes.text_x.geometry} material={sixth_texture_atlas_material} position={[5.476, 0.336, 0.692]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="text_zero_one" geometry={nodes.text_zero_one.geometry} material={sixth_texture_atlas_material} position={[5.631, 0.336, -0.722]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="text_antiquity" geometry={nodes.text_antiquity.geometry} material={sixth_texture_atlas_material} position={[5.361, 0.157, 0.693]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="text_turing_machines" geometry={nodes.text_turing_machines.geometry} material={sixth_texture_atlas_material} position={[5.361, 0.123, 0.746]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh name="backdrop" geometry={nodes.backdrop.geometry} material={first_texture_atlas_material} position={[-6.989, 2.881, 0.015]} />
      <mesh name="character_head_on_fire" geometry={nodes.character_head_on_fire.geometry} material={second_texture_atlas_material} position={[1.553, 0.205, -1.001]} />
      <mesh name="character_half_cut" geometry={nodes.character_half_cut.geometry} material={second_texture_atlas_material} position={[2.021, 0.297, -1.712]} />
      <mesh name="character_ice_cream" geometry={nodes.character_ice_cream.geometry} material={third_texture_atlas_material} position={[1.464, 0.322, -1.305]} />
      <mesh name="character_straw_man" geometry={nodes.character_straw_man.geometry} material={third_texture_atlas_material} position={[1.672, 0.271, -1.578]} />
      <mesh name="character_michael_myers" geometry={nodes.character_michael_myers.geometry} material={third_texture_atlas_material} position={[3.054, 0.252, -0.075]} />
      <mesh name="dish_bread" geometry={nodes.dish_bread.geometry} material={fourth_texture_atlas_material} position={[4.91, 0.036, 0.404]} />
      <mesh name="character_hen" geometry={nodes.character_hen.geometry} material={third_texture_atlas_material} position={[2.551, 0.08, -1.189]} />
      <mesh name="character_walkman" geometry={nodes.character_walkman.geometry} material={fourth_texture_atlas_material} position={[3.952, 0.155, 0.699]} />
      <mesh name="tv_model_1" geometry={nodes.tv_model_1.geometry} material={seventh_texture_atlas_material} position={[1.861, 0.101, 0.803]} />
      <mesh name="tv_model_2" geometry={nodes.tv_model_2.geometry} material={seventh_texture_atlas_material} position={[2.087, 0.363, 1.312]} />
      <mesh name="tv_model_3" geometry={nodes.tv_model_3.geometry} material={seventh_texture_atlas_material} position={[1.91, 0.636, 1.108]} />
      <mesh name="tv_model_4" geometry={nodes.tv_model_4.geometry} material={eight_texture_atlas_material} position={[1.958, 0.103, 1.105]} />
      <mesh name="tv_model_5" geometry={nodes.tv_model_5.geometry} material={eight_texture_atlas_material} position={[2.132, 0.114, 1.373]} />
      <mesh name="tv_model_6" geometry={nodes.tv_model_6.geometry} material={eight_texture_atlas_material} position={[1.937, 0.47, 1.104]} />
      <mesh name="tv_model_7" geometry={nodes.tv_model_7.geometry} material={eight_texture_atlas_material} position={[1.889, 0.301, 1.062]} />
      <mesh name="heart" geometry={nodes.heart.geometry} material={fifth_texture_atlas_material} position={[2.97, 0.906, -0.065]} />
      <mesh name="gameboy" geometry={nodes.gameboy.geometry} material={fifth_texture_atlas_material} position={[4.031, 0.11, 0.872]} />
      <mesh name="bomb_cube_1" geometry={nodes.bomb_cube_1.geometry} material={second_texture_atlas_material} position={[4.729, 0.075, -0.285]} />
      <mesh name="monster_1" geometry={nodes.monster_1.geometry} material={fifth_texture_atlas_material} position={[4.72, 0.08, -0.672]} />
      <mesh name="monster_2" geometry={nodes.monster_2.geometry} material={fifth_texture_atlas_material} position={[4.466, 0.088, 0.382]} />
      <mesh name="bomb_box_2" geometry={nodes.bomb_box_2.geometry} material={second_texture_atlas_material} position={[4.675, 0.077, -0.125]} />
      <mesh name="character_magician" geometry={nodes.character_magician.geometry} material={third_texture_atlas_material} position={[3.326, 0.245, 0.23]} />
      <mesh name="character_walter_white" geometry={nodes.character_walter_white.geometry} material={fourth_texture_atlas_material} position={[3.336, 0.223, -0.368]} />
      <mesh name="monster_3" geometry={nodes.monster_3.geometry} material={fifth_texture_atlas_material} position={[4.528, 0.092, 0.203]} />
      <mesh name="character_glasses" geometry={nodes.character_glasses.geometry} material={second_texture_atlas_material} position={[1.135, 0.298, 2.057]} />
      <mesh name="cookies" geometry={nodes.cookies.geometry} material={fourth_texture_atlas_material} position={[4.615, 0.02, -0.468]} />
      <mesh name="cup" geometry={nodes.cup.geometry} material={fourth_texture_atlas_material} position={[4.869, 0.045, -0.531]} />
    </group>
  )
}

useGLTF.preload('/main.gltf')
